openapi: 3.0.3
info:
    title: Laravel
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://sockets.test'
paths:
    /api/v1/cities:
        get:
            summary: 'Get all cities Data'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "[{\n  \"id\": 1,\n  \"country_code\": \"RU\",\n  \"name\": \"Moscow\",\n}]"
            tags:
                - Cities
            security: []
        post:
            summary: 'Update city'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "{\n  \"id\": 1,\n  \"country_code\": \"RU\",\n  \"name\": \"Moscow\",\n}"
            tags:
                - Cities
            security: []
    '/api/v1/cities/{city}':
        get:
            summary: 'Show city Data'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "{\n  \"id\": 1,\n  \"country_code\": \"RU\",\n  \"name\": \"Moscow\",\n}"
            tags:
                - Cities
            security: []
        put:
            summary: 'Update City Data'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "{\n  \"id\": 1,\n  \"country_code\": \"RU\",\n  \"name\": \"Moscow\",\n}"
            tags:
                - Cities
            security: []
        delete:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
            security: []
        parameters:
            -
                in: path
                name: city
                description: ''
                example: placeat
                required: true
                schema:
                    type: string
    /api/v1/companies:
        post:
            summary: 'Store Company Data Companies'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Companies
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                city_id:
                                    type: string
                                    description: ''
                                    example: quis
                                name:
                                    type: string
                                    description: ''
                                    example: sit
                                description:
                                    type: string
                                    description: ''
                                    example: {  }
                            required:
                                - city_id
                                - name
            security: []
    /api/v1/user:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: Unauthenticated.
                                properties:
                                    message: { type: string, example: Unauthenticated. }
            tags:
                - Endpoints
            security: []
